development:
  adapter: postgresql
  database: problemlist_dev
  username: postgres
  password: postgres
  host: localhost
  
test:
  adapter: postgresql
  database: problemlist_test
  username: postgres
  password: postgres
  host: localhost
  
production:
  adapter: postgresql
  database: problemlist_prod
  username: postgres
  password: postgres
  host: localhost
